# Animal-Face GG-VAE - MGDA LN Aggregator
dataset: oxford-flower-102
data_dir: ../data
normalize: false
arch: gg_vae
latent_dim: 4096
hidden_dims: [32, 64, 128, 256, 512]
loss_weights: [1.0, 0.1255, 1.0]
recons_dist: bernoulli
recons_reduction: mean
epochs: 1000
batch_size: 128
optimizer: adamw
lr: 0.001
wd: 0.0
scheduler: cosine
scheduler_lr_min: 1e-6
aggregator: mgda_ln
seed: 123123
save_path: logs/
save_freq: 100
eval_freq: 1
num_samples: 4
hv_ref: [1.1, 1.1, 1.1]
use_wandb: true
wandb_project: mo-vae
wandb_entity: rasa_research
wandb_name: oxford_flower_102-gg_vae-128d-mgda_ln-seed123123
wandb_group: oxford_flower_102-gg_vae-128d-mgda_ln
