dataset: CelebA
data_dir: ../data
normalize_inputs: false
arch: vq_vae
embedding_dim: 64
num_embeddings: 512
hidden_dims:
- 128
- 256
loss_weights:
  reconstruction_loss: 1.0
  embedding_loss: 1.0
  commitment_loss: 0.25
recons_objective: bce
recons_activation: sigmoid
epochs: 100
batch_size: 128
optimizer: adam
lr: 3e-4
wd: 0.0
aggregator: jd_sum
seed: 12341234
save_path: logs/
save_freq: 10
eval_freq: 10
num_vis_samples: 9
hv_ref:
  reconstruction_loss: 1.1
  embedding_loss: 1.1
  commitment_loss: 1.1
use_wandb: true
wandb_project: mo-vae
wandb_entity: rasa_research
wandb_name: celeba vq_vae 512k 64d bce jd_sum seed12341234
wandb_group: celeba vq_vae 512k 64d bce jd_sum
