dataset: oxford-flower-102
data_dir: ../data
normalize_inputs: false
arch: gg_vq_vae_v3
embedding_dim: 64
num_embeddings: 512
hidden_dims:
- 128
- 256
loss_weights:
  reconstruction_loss: 1.0
  embedding_loss: 1.0
  commitment_loss: 0.25
  gradient_guided_loss: 1.0
  edge_matching_loss: 1.0
recons_objective: bce
recons_activation: sigmoid
epochs: 1000
batch_size: 128
optimizer: adam
lr: 1e-4
wd: 0.0
scheduler: cosine
scheduler_lr_min: 1e-6
aggregator: mgda_lgn
seed: 42
save_path: logs/
save_freq: 200
eval_freq: 200
num_vis_samples: 4
hv_ref:
  reconstruction_loss: 1.1
  gradient_guided_loss: 1.1
  embedding_loss: 1.1
  commitment_loss: 1.1
  edge_matching_loss: 1.1
use_wandb: true
wandb_project: mo-vae
wandb_entity: rasa_research
wandb_name: oxford_flower_102-gg_vq_vae_v3-512k-64d-mgda_lgn-seed42
wandb_group: oxford_flower_102-gg_vq_vae_v3-512k-64d-mgda_lgn
