dataset: cifar100
data_dir: ../data
normalize_inputs: false
arch: gg_vae_v4
latent_dim: 128
hidden_dims:
- 32
- 64
- 128
loss_weights:
  reconstruction_loss: 1.0
  kld_loss: 0.00512
  gradient_guided_loss: 1.0
  edge_matching_loss: 1.0
recons_objective: bce
recons_activation: sigmoid
hv_ref:
  reconstruction_loss: 1.1
  kld_loss: 1.1
  gradient_guided_loss: 1.1
  edge_matching_loss: 1.1
epochs: 200
batch_size: 256
optimizer: adam
lr: 1e-4
scheduler: cosine
scheduler_lr_min: 1e-6
wd: 0.0
aggregator: mgda_lgn
seed: 42
save_path: logs/
save_freq: 20
eval_freq: 20
num_vis_samples: 9
use_wandb: true
wandb_project: mo-vae
wandb_entity: rasa_research
wandb_name: cifar100-gg_vae_v4-128d-bce-mgda_lgn-seed42
wandb_group: cifar100-gg_vae_v4-128d-bce-mgda_lgn
