# CelebA GG-VAE - 10ep 64bs - MGDA L2 norm
dataset: CelebA
data_dir: ../data
normalize: false
arch: vae
latent_dim: 1024
hidden_dims: [32, 64, 128, 256, 512]
loss_weights: [1.0, 1.573e-3]
recons_dist: bernoulli
recons_reduction: mean
epochs: 100
batch_size: 256
optimizer: adam
lr: 0.001
wd: 1e-5
scheduler: exponential
scheduler_gamma: 0.95
aggregator: mgda_ln
mgda_epsilon: 1e-5
mgda_max_iters: 250
seed: 123
save_path: logs/
save_freq: 10
eval_freq: 1
num_samples: 9
hv_ref: [1.1, 1.1]
use_wandb: true
wandb_project: mo-vae
wandb_entity: rasa_research
wandb_name: celeba vae w_kl=7.86e-4 lr1e-3 wd1e-5 mgda_l2 seed123
wandb_group: celeba vae w_kl=7.86e-4 lr1e-3 wd1e-5 mgda_l2
