# CelebA Recursive Cyclic VAE - MGDA loss+ (LGN)
dataset: CelebA
data_dir: ../data
normalize: false
arch: recursive_cyclic_vae
latent_dim: 128
hidden_dims: [32, 64, 128, 256, 512]
loss_weights: [1.0, 1.573e-3, 0.00025]
recons_dist: bernoulli
recons_reduction: mean
epochs: 100
batch_size: 256
optimizer: adam
lr: 0.001
wd: 1e-5
scheduler: exponential
scheduler_gamma: 0.95
aggregator: mgda_lgn
mgda_epsilon: 1e-5
mgda_max_iters: 250
recursive_kld_anneal_steps: 25000
seed: 42
save_path: logs/
save_freq: 10
eval_freq: 1
num_samples: 9
hv_ref: [1.1, 1.1, 1.1]
use_wandb: true
wandb_project: mo-vae
wandb_entity: rasa_research
wandb_name: celeba rc_vae mgda_lgn ann25k lr1e-3 wd1e-5 seed42
wandb_group: celeba rc_vae mgda_lgn ann25k lr1e-3 wd1e-5