dataset: CelebA
data_dir: ../data
normalize_inputs: true
arch: gg_vae_v5
latent_dim: 1024
hidden_dims:
- 32
- 64
- 128
- 256
- 512
loss_weights:
  reconstruction_loss: 1.0
  kld_loss: 0.001573
  gradient_guided_loss: 1.0
  edge_matching_loss: 1.0
recons_objective: mse
recons_activation: none
epochs: 100
batch_size: 256
optimizer: adam
lr: 0.001
wd: 1e-5
scheduler: exponential
scheduler_gamma: 0.95
aggregator: mgda_lgn
mgda_epsilon: 1e-5
mgda_max_iters: 250
seed: 123123
save_path: logs/
save_freq: 10
eval_freq: 1
num_vis_samples: 9
hv_ref:
  reconstruction_loss: 1.1
  kld_loss: 1.1
  gradient_guided_loss: 1.1
  edge_matching_loss: 1.1
use_wandb: true
wandb_project: mo-vae
wandb_entity: rasa_research
wandb_name: celeba gg_vae_v5 w_kl=1.573e-3 lr1e-3 wd1e-5 mgda_lgn seed123123123-mse
wandb_group: celeba gg_vae_v5 w_kl=1.573e-3 lr1e-3 wd1e-mse-5 mgda_lgn
